name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.x'
    - name: Install Python build dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
    - name: Install project dependencies
      run: |
        pip install -e .[dev]
    - name: Run Flake8 Linter
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics
    - name: Run MyPy Type Checker
      run: |
        mypy .
    - name: Run Bandit Security Linter
      run: |
        bandit -r . -ll -x tests
    - name: Run Pytest Tests
      run: |
        pytest

  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t voxunity-ai:latest .

  deploy-docs:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.x'
    - name: Install MkDocs and Material Theme
      run: |
        pip install mkdocs mkdocs-material
    - name: Deploy docs
      run: mkdocs gh-deploy --force
